es:
  build: elasticsearch/.
  ports:
  - 9200:9200
  - 9300:9300
kibana:
  image: kibana:4.1.4
  links:
  - es:elasticsearch 
  ports:
  - 5601:5601
webclient:
  build: webClientEs/.
  links:
  - es:elasticsearch
  ports:
  - 8080:8080
